name: CR Status Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-cr-status:
    runs-on: ubuntu-latest
    steps:
      - name: Call CR Status Webhook
        run: |
          # Call your webhook and capture the HTTP status
          STATUS=$(curl -s -o response.txt -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d '{"crId":"ABC"}' \
            https://725414d3c0bf.ngrok-free.app/webhook)
          cat response.txt
          # Fail the job if status is not 200
          if [ "$STATUS" -ne 200 ]; then
            echo "CR is not approved. Blocking merge."
            exit 1
          fi
